---
title: Template for DT
author: Paul V. Desanker
date: '2021-04-15'
slug: []
categories:
  - sample-page
tags:
  - sample-page
---
```{r}
dt <-  datatable(
  head(iris, 20), 
  options = list(
     columnDefs = list(list(className = 'dt-center', targets = 5)),
     pageLength = 5, lengthMenu = c(5, 10, 15, 20)),
  fillContainer = T)

frameWidget(dt, height = 350, width = '95%')

```


> **Sample table with pages and sortable by column**

DataTables displays R matrices or data frames as interactive HTML tables that support filtering, pagination, and sorting.

http://rstudio.github.io/DT/

if (!require("DT")) install.packages('DT')

```{r}
library(DT)
datatable(iris, options = list(pageLength = 5))
```

```{r}
library(tidyverse)
library(DT)

iris %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
                                             
```                                        



